package com.intigral.assignment.utils.response;

public enum ErrorCode {
    INTERNAL_SERVER_ERROR,
    MISSING_NAME, INVALID_NAME,
    MISSING_DESCRIPTION, INVALID_DESCRIPTION,
    MISSING_RACK_ID, INVALID_RACK_ID, RACK_ID_ALREADY_ALLOCATED, RACK_ID_NOT_EXIST;
}
